### ISSUE TITLE
Error when trying to save to subfolder

### ISSUE THREAD

**Issue by BlenderDefender** [BlenderDefender/blender_project_starter#7]
**Describe the bug**
Using Auto Setup, Subfolders are created, but the subfolder added to the Blender File path seems to be a raw string and not converted to path, resulting in an issue.

**To Reproduce**
1. Go to the addon preferences
2. Set one Folder to be a folder path with a subfolder (Folder>>Subfolder)
3. Restart Blender, so the changes take affect
4. Go to the "Blender Project Starter" panel
5. Set the Blender Target Location to the Subfolder Path
6. Click on "Build Project"
7. See error

**Expected behavior**
The addon saves the Blender File to the selected subfolder

**Expected Fix**
In the get subfolder function, Convert the Output to path.

**Error Warning**
location: :-1
Error: Python: Traceback (most recent call last):
File "/home/blenderdefender/.config/blender/2.91/scripts/addons/blender_project_starter-multi_folder_support/operators.py", line 87, in execute
save_file(context, filename, subfolder)
File "/home/blenderdefender/.config/blender/2.91/scripts/addons/blender_project_starter-multi_folder_support/functions/main_functions.py", line 91, in save_file
relative_remap=context.scene.remap_relative
File "/snap/blender/65/2.91/scripts/modules/bpy/ops.py", line 132, in call
ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot open file /home/blenderdefender/My_Project/Bilder und Texturen>>Renderergebnisse/File.blend@ for writing: No such file or directory

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Blender Version [2.91]

**Comment by BlenderDefender** [comment]
Fixed, but the issue remains open until the development branch is merged into master.
