### ISSUE TITLE
Error when trying to build without specifying any Folders within the Root Folder

### ISSUE THREAD

**Issue by BlenderDefender** [BlenderDefender/blender_project_starter#8]
**Describe the bug**
When using Custom Setup without any Folders in the project folder, the Project Folder isn't created, resulting in an Error (Blend File can't be saved)

**To Reproduce**
1. Go to the Blender Project Starter Panel
2. Select the Custom Folders Option 
3. Build directory without adding any folders
4. See Error

**Expected behavior**
The Project Folder is created and the file is saved within the folder.

**Expected Fix**
Build Project Root Folder independently from the Folders within the Root Folder. 

**Error Warning**
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/blenderdefender/.config/blender/2.91/scripts/addons/blender_project_starter-multi_folder_support/operators.py", line 87, in execute
    save_file(context, filename, subfolder)
  File "/home/blenderdefender/.config/blender/2.91/scripts/addons/blender_project_starter-multi_folder_support/functions/main_functions.py", line 91, in save_file
    relative_remap=context.scene.remap_relative
  File "/snap/blender/65/2.91/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot open file /home/blenderdefender/Custom_Setup_New_File/Custom_Setup_New_File.blend@ for writing: No such file or directory

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Blender Version [2.91]

**Comment by BlenderDefender** [comment]
Fixed, but the issue remains open until the development branch is merged into master.
